name: Deploy React App
on:
  push:
    branches:
      - main
    paths-ignore:
      - './github/workflows/*'
jobs:
  test_my_app:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test app
        run: npm run test
  lint:
    runs-on: windows-latest
    needs: test_my_app
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint app
        run: npm run lint
  build_app:
    runs-on: windows-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo Deploying...